# Generated by Django 3.1.2 on 2020-11-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=30)),
                ('Nombres', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=30)),
                ('Nit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ropass', models.CharField(choices=[('C', 'Camisa'), ('P', 'Pantalon'), ('S', 'Sueter')], default='C', max_length=1)),
                ('cantidad', models.PositiveIntegerField(default=True)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Numero', models.CharField(max_length=15)),
                ('Fecha', models.DateField()),
                ('CVV', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.DateTimeField(auto_now=True)),
                ('Facturacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.facturacion')),
                ('Ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.ropa')),
                ('Tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tarjeta')),
            ],
        ),
    ]
